events/events/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_events.urls', namespace='events')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/music_events/urls.py
from django.urls import path
from . import views

app_name = 'music_events'
urlpatterns = [
    path('', views.homepage, name='homepage'),

    # Venue-related
    path('venues/list/', views.venue_list, name='venue_list'),
    path('venues/detail/<int:venue_pk>/', views.venue_detail, name='venue_detail'),
    path('venues/artists_at/<int:venue_pk>/', views.artists_at_venue, name='artists_at_venue'),

    # Artist related
    path('artists/list/', views.artist_list, name='artist_list'),
    path('artists/detail/<int:artist_pk>/', views.artist_detail, name='artist_detail'),
    path('artists/edit/<int:artist_pk>/', views.edit_artist, name='edit_artist'),
    path('artists/delete/<int:artist_pk>/', views.delete_artist, name='delete_artist'),
    path('artists/venues_played/<int:artist_pk>/', views.venues_for_artist, name='venues_for_artist'),
]

events/music_events/models.py
from django.db import models


# Create your models here.
class Artist(models.Model):
    """ Represents a musician or a band - a music artist """
    name = models.CharField(max_length=200, blank=False)
    description = models.CharField(max_length=400, blank=True)
    genre = models.CharField(max_length=20, blank=True)
    nationality = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return f'Name: {self.name}'


class Venue(models.Model):
    """ Represents a venue, that hosts shows. """
    name = models.CharField(max_length=200, blank=False, unique=True)
    city = models.CharField(max_length=200, blank=False)
    state = models.CharField(max_length=2, blank=False)

    def __str__(self):
        return f'Name: {self.name} Location: {self.city}, {self.state}'


class Show(models.Model):
    """ One Artist playing at one Venue at a particular date and time. """
    show_date = models.DateTimeField(blank=False)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)

    def __str__(self):
        return f'Artist: {self.artist} At: {self.venue} On: {self.show_date}'

events/music_events/forms.py
from django import forms
from .models import Artist


class VenueSearchForm(forms.Form):
    search_name = forms.CharField(label='Venue Name', max_length=200)


class ArtistSearchForm(forms.Form):
    search_name = forms.CharField(label='Artist Name', max_length=200)


class NewArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ('description', 'genre', 'nationality')

events/music_events/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q

from .models import Venue, Show, Artist
from .forms import VenueSearchForm, ArtistSearchForm, NewArtistForm


# Create your views here.
def homepage(request):
    return render(request, 'music_events/home.html')


def venue_list(request):
    form = VenueSearchForm()
    search_name = request.GET.get('search_name')

    if search_name:
        # search for this venue, display results. Use case-insensitive contains
        venues_results = Venue.objects.filter(Q(name__icontains=search_name) | Q(city__icontains=search_name)).order_by('name')
    else:
        venues_results = Venue.objects.all().order_by('name')

    # venues_list = Venue.objects.all().order_by('name')
    # context =
    return render(request, 'music_events/venues/venue_list.html',
                  {'venues': venues_results,
                   'form': form,
                   'search_term': search_name})


def artists_at_venue(request, venue_pk):  # pk = venue_pk
    """ Get all artists who have played a show at the venue with pk provided """

    shows = Show.objects.filter(venue=venue_pk).order_by('-show_date')
    venue = get_object_or_404(Venue, pk=venue_pk)

    return render(request, 'music_events/artists/artist_list_for_venue.html', {'venue': venue, 'shows': shows})


def venue_detail(request, venue_pk):
    venue = get_object_or_404(Venue, pk=venue_pk)
    return render(request, 'music_events/venues/venue_detail.html', {'venue': venue})


def artist_list(request):
    """ Get a list of all artists, ordered by name.

        If request contains a get parameter search_name then
        only include artists with names containing that text. """
    form = ArtistSearchForm()
    search_name = request.GET.get('search_name')
    if search_name:
        artists_results = Artist.objects.filter(Q(name__icontains=search_name) | Q(genre__icontains=search_name)).order_by('name')
    else:
        artists_results = Artist.objects.all().order_by('name')

    return render(request, 'music_events/artists/artists_list.html',
                  {'artists': artists_results,
                   'form': form,
                   'search_term': search_name})


def artist_detail(request, artist_pk):
    """ Details about one artist """
    artist = get_object_or_404(Artist, pk=artist_pk)
    return render(request, 'music_events/artists/artist_detail.html', {'artist': artist})


def edit_artist(request, artist_pk):
    """Updates note"""
    artist = get_object_or_404(Artist, pk=artist_pk)

    form = NewArtistForm(request.POST or None, instance=artist)
    if form.is_valid():
        form.save()
        # messages.info(request, 'Artist updated')
        return redirect('events:artist_list')
    return render(request, 'music_events/artists/edit_artist.html',
                  {'artist': artist,
                   'form': form})


def delete_artist(request, artist_pk):
    """deletes note"""
    artist = get_object_or_404(Artist, pk=artist_pk)

    artist.delete()
    # messages.info(request, 'Note Deleted')
    return redirect('events:artist_list')


def venues_for_artist(request, artist_pk):
    """ Get all of the venues where this artist has played a show """
    shows = Show.objects.filter(artist=artist_pk).order_by('-show_date')  # most recent first
    artist = Artist.objects.get(pk=artist_pk)

    return render(request, 'music_events/venues/venue_list_for_artist.html', {'artist': artist, 'shows': shows})

events/music_events/templates/music_events/artists/artist_detail.html
{% extends 'music_events/base.html' %} {% block content %}

<h2 id="artist-detail-title">Artist Detail</h2>
<div class="row">
  <h3 id="artist-name">{{ artist.name }}</h3>
  <p class="item-nationality">{{ artist.nationality }}</p>
  <p class="item-genre">{{ artist.genre }}</p>
  <p class="item-description"><span>Info:</span> {{ artist.description }}</p>
</div>
<div class="options">
  <a class="edit" href="{% url 'events:edit_artist' artist_pk=artist.pk %}">Edit</a>

  <form action="{% url 'events:delete_artist' artist.pk %}" method="post">
    {% csrf_token %}
    <button type="submit" class="delete btn">Delete</button>
  </form>
</div>
{% endblock %}

events/music_events/templates/music_events/artists/artist_list_for_venue.html
{% extends 'music_events/base.html' %} {% block content %}

<h2 id="artists-at-venue-title">
  Artists that have played or will play at {{ venue.name }}
</h2>

<div class="list">
  {% for show in shows %}

  <div class="show row" id="show_{{ show.pk }}">
    <p>
      <strong> {{ show.artist.name }}</strong> on {{ show.show_date }}
{#      <a href="{% url 'notes_for_show' show_pk=show.pk %}"#}
{#        >See notes for this show, and add your own</a#}
{#      >#}
    </p>
  </div>

  {% empty %}

  <p id="no-results">We have no records of shows at this venue.</p>
</div>

{% endfor %} {% endblock %}

events/music_events/templates/music_events/artists/artists_list.html
{% extends 'music_events/base.html' %} {% block content %}

<h2>Artists List</h2>

<div>
  <p>Artist Search</p>
  <form action="{% url 'events:artist_list' %}">
    {{ form }}
    <input type="submit" value="Search" class="btn" />
  </form>

  <div class="filtered-results">
    {% if search_term %}
    <h2 id="artist-list-title">
      Artists matching '{{ search_term }}'
      <a href="{% url 'events:artist_list' %}" id="clear_search">(clear)</a>
    </h2>
    {% else %}
    <h2 id="artist-list-title">All artists</h2>
    {% endif %}
  </div>
  <div class="list">
    {% for artist in artists %}

    <div class="artist row" id="artist_{{ artist.pk }}">
      <p class="item-name">{{ artist.name }}</p>
      <p class="item-nationality">{{ artist.nationality }}</p>
      <p class="item-genre">Genre: {{ artist.genre }}</p>
      <p class="item-description">See artist
          <a href="{% url 'events:artist_detail' artist_pk=artist.pk %}">details</a>
          or
          <a href="{% url 'events:venues_for_artist' artist_pk=artist.pk %}">shows</a>
      </p>
    </div>

    {% empty %}

    <p>No artists found</p>
    {% endfor %}
  </div>
</div>

{% endblock %}

events/music_events/templates/music_events/artists/edit_artist.html
{% extends 'music_events/base.html' %}

{% block content %}

<h2>Edit details for {{ artist.name }}</h2>

<form class="edit-form" method="POST" action="{% url 'events:edit_artist' artist_pk=artist.pk %}">
  <div>
    {% csrf_token %}
    {{ form.as_p }}
  </div>
  <div class="edit-form-options">
    <input class="edit btn" type="submit" value="Update">
    <button class="cancel btn"><a href="{% url 'events:artist_list' %}">Cancel</a></button>
  </div>
</form>
{% endblock %}

events/music_events/templates/music_events/base.html
{% load static %}
<html lang="en">
<head>
  <title>MUSIC EVENTS</title>
  <link rel="stylesheet" href="{% static 'css/global.css' %}" type="text/css" />
</head>

<body>
    <header>
      <h1>MUSIC EVENTS</h1>
      <div>
        <a href="{% url 'events:homepage' %}">Home</a>
        <a href="{% url 'events:venue_list' %}">Venues</a>
        <a href="{% url 'events:artist_list' %}">Artists</a>
        {#  <a href="{% url 'events:show_list' %}">Shows</a>#}
      </div>

    </header>
    <hr>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <footer>
        <p>Created by: <span>Fernando Molano</span></p>
    </footer>

</body>
</html>

events/music_events/templates/music_events/home.html
{% extends 'music_events/base.html' %}

{% block content %}
<div class="home-container">
    <div>
        <p>Welcome to Music Events Website</p>
        <p>Use the links above to navigate</p>
    </div>
</div>

{% endblock %}

events/music_events/templates/music_events/venues/venue_detail.html
{% extends 'music_events/base.html' %} {% block content %}

<h2 id="venue-detail-title">Venue Detail</h2>

<div class="row">
  <h3 id="venue-name">{{ venue.name }}</h3>
  <p>
    <span id="venue-city">{{ venue.city }}</span>
    <span id="venue-state">{{ venue.state }}</span>
  </p>
</div>

{% endblock %}

events/music_events/templates/music_events/venues/venue_list.html
{% extends 'music_events/base.html' %} {% block content %}

<h2>Venue List</h2>

<div>
  <p>Venue Search</p>
  <form action="{% url 'events:venue_list' %}">
    {{ form }}
    <input type="submit" class="btn" value="Search" />
  </form>

  <div class="filtered-results">
    {% if search_term %}
    <h3 id="venue-list-title">
      Venues matching '{{ search_term }}'
      <a href="{% url 'events:venue_list' %}" id="clear_search">clear</a>
    </h3>
    {% else %}
    <h3 id="venue-list-title">All venues</h3>
    {% endif %}
  </div>

    <div class="list">
        {% for venue in venues %}

        <div id="venue-{{ venue.pk }}" class="row">
          <p class="item-name">
            <a href="{% url 'events:venue_detail' venue_pk=venue.pk %}"
              >{{ venue.name }}</a
            >
          </p>
          <p class="item-location">Location: {{ venue.city }}, {{ venue.state }}</p>
          <p>
            See artists presenting at
            <a href="{% url 'events:artists_at_venue' venue_pk=venue.pk %}"
              >{{ venue.name }}</a
            >
          </p>
        </div>

        {% empty %}
        <p>No venues found</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

events/music_events/templates/music_events/venues/venue_list_for_artist.html
{% extends 'music_events/base.html' %} {% block content %}

<h2 id="venues-for-artist-title">
  Venues where {{ artist.name }} has played/will play at
</h2>
<div class="list">
  {% for show in shows %}

  <div class="show row" id="show-{{ show.pk }}">
      <p><span class="item-name">{{ show.venue.name}}</span> on {{ show.show_date }}</p>
  </div>
  {% empty %}
  <p id="no-results">We have no records of venues this artist has played at</p>
  <p>{% endfor %}</p>
</div>
{% endblock %}